DroneBook.WebUI/ViewModels/DroneListViewModel.cs
namespace DroneBook.WebUI.ViewModels
{
    using System.Collections.Generic;

    public class DroneListViewModel
    {
        private List<DroneViewModel> _drones;

        public List<DroneViewModel> Drones
        {
            get
            {
                if (_drones == null)
                {
                    _drones = new List<DroneViewModel>();
                } 

                return _drones;
            }
            set { _drones = value; }
        }
    }
}

DroneBook.WebUI/ViewModels/DroneViewModel.cs
using DroneBook.BusinessLogic.Services;

namespace DroneBook.WebUI.ViewModels
{
    public class DroneViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public int Size { get; set; }

        public DroneViewModel()
        {            
        }

        public DroneViewModel(Drone drone)
        {
            this.Name = drone.Name;
            this.Description = drone.Description;
            this.Type = drone.Type;
            Size = drone.Size;
        }
    }
}

DroneBook.WebUI/Controllers/CreateDroneController.cs
namespace DroneBook.WebUI.Controllers
{
    using System.Collections.Generic;
    using System.Web.Mvc;
    using BusinessLogic.Services;
    using WebApi.ViewModel;


    public class CreateDroneController : Controller
    {

        public ViewResult Create()
        {
            var model = new CreateDroneViewModel();
            model.Parts = new List<PartsViewModel>()
            {
                new PartsViewModel() {PartType = PartType.Controller},
                new PartsViewModel() {PartType = PartType.ESC},
                new PartsViewModel() {PartType = PartType.Rotors},
                new PartsViewModel() {PartType = PartType.Props},
                new PartsViewModel() {PartType = PartType.Receiver},
            };
            return View(model);
        }

    }
}

DroneBook.WebUI/Controllers/DefaultController.cs
namespace DroneBook.WebUI.Controllers
{
    using System.Collections.Generic;
    using System.Web.Http;

    public class DefaultController : ApiController
    {
        // GET: api/Default
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET: api/Default/5
        public string Get(int id)
        {
            return "value";
        }

        // POST: api/Default
        public void Post([FromBody]string value)
        {
        }

        // PUT: api/Default/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/Default/5
        public void Delete(int id)
        {
        }
    }
}

DroneBook.WebUI/Controllers/DroneController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DroneBook.BusinessLogic.Services;
using DroneBook.WebUI.ViewModels;

namespace DroneBook.WebUI.Controllers
{
    using System.Net.Http;
    using Infrastructure;
    using Newtonsoft.Json;

    public class DroneController : Controller
    {
        public ActionResult List()
        {
            return View();
        }

        public ActionResult Detail(int id)
        {
            HttpClient client = new HttpClient();
            string json = client.GetStringAsync(new Uri(Constants.WebApiAddres + id)).Result;
            Drone drone = JsonConvert.DeserializeObject<Drone>(json);

            return View(drone);
        }
    }
}

DroneBook.WebUI/Controllers/ProbyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DroneBook.WebUI.Controllers
{
    using System.ComponentModel;
    using Newtonsoft.Json;

    public class ProbyController : Controller
    {
        // GET: Proby
        public ActionResult Index()
        {
            ProbyViewModel model = new ProbyViewModel()
            {
                Names = new List<Complextype>()
                {
                    new Complextype()
                    {
                        Name = "Kuba",
                        Type = TypesViewModel.Pierwsa
                    },
                    new Complextype()
                    {
                        Name = "Maciek",
                        Type = TypesViewModel.Druga
                    }
                }
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(ProbyViewModel model)
        {
            return View(model);
        }
    }

    public class ProbyViewModel
    {
        public string Text { get; set; }
        public List<Complextype> Names { get; set; }
    }

    public class Complextype
    {
        public string Name { get; set; }
        public TypesViewModel Type { get; set; }
    }

    public enum TypesViewModel
    {
        [Description("cos1")]
        Pierwsa=1,
        [Description("cos2")]
        Druga
    }
}

DroneBook.WebUI/Views/CreateDrone/Create.cshtml
@model DroneBook.WebApi.ViewModel.CreateDroneViewModel

@{
    ViewBag.Title = "DroneBook - Create your drone ";
}


<div style="display: inline-block; width: 800px">
    <div class="item-holder">
        <h4 class="h4">Basics</h4>
        <div id="0" data-bind="slideToggle: $root.currentPage() === 0">
            <h5 class="h5">Name</h5>
            <p>@Html.TextBoxFor(m => m.Name, new { @class = "form-control", data_Bind = "value: $root.Drone.Name, hasFocus: $root.currentPage() === 0" }) </p>
            <h5 class="h5">Description</h5>
            <p>@Html.TextBoxFor(m => m.Description, new { @class = "form-control", data_Bind = "value: $root.Drone.Description" }) </p>
            <h5 class="h5">Type</h5>
            <p>@Html.TextBoxFor(m => m.Type, new { @class = "form-control", data_Bind = "value: $root.Drone.Type" }) </p>
            <h5 class="h5">Size</h5>
            <p>@Html.TextBoxFor(m => m.Size, new { @class = "form-control", data_Bind = "value: $root.Drone.Size" }) </p>
            <hr />
        </div>
    </div>
    <div class="item-holder">
        <h4 class="h4">Parts</h4>
        <div id="1" data-bind="slideToggle: $root.currentPage() === 1">
            <div id="PartsList">
                <h5 class="h5">Controller</h5>
                <p id="part">
                    @Html.TextBoxFor(m => m.Parts[0].Name, new { @class = "form-control", data_Bind = "value: $root.Drone.Controller, hasFocus: $root.currentPage() === 1" })
                    @Html.EnumDropDownListFor(m => m.Parts[0].PartType, new { @class = "form-control", @style = "display: none" })
                </p>
                <h5 class="h5">ESC</h5>
                <p>
                    @Html.TextBoxFor(m => m.Parts[1].Name, new { @class = "form-control", data_Bind = "value: $root.Drone.ESC" })
                    @Html.EnumDropDownListFor(m => m.Parts[1].PartType, new { @class = "form-control", @style = "display: none" })
                </p>
                <h5 class="h5">Rotors</h5>
                <p>
                    @Html.TextBoxFor(m => m.Parts[2].Name, new { @class = "form-control", data_Bind = "value: $root.Drone.Rotors" })
                    @Html.EnumDropDownListFor(m => m.Parts[2].PartType, new { @class = "form-control", @style = "display: none" })
                </p>
                <hr />
            </div>
            <input id="AddField" class="btn" type="button" value="Add new Field" />
            <hr />
        </div>
    </div>
    <div class="item-holder">
        <h4 class="h4">Image</h4>
        <div id="2" data-bind="slideToggle: $root.currentPage() === 2">
            <br />
            <input type="file" id="files" name="files[]" multiple />
            <br />
        </div>
    </div>
</div>
<div style="display: inline-block; vertical-align: top">
    <div class="item-holder">
        <h2 class="h2">Summary</h2>
        <div>
            <strong>Your drone:</strong><br />
            <output id="list"></output> <br /><br />
            <strong>Name:</strong> <span data-bind="text: $root.Drone.Name"></span><br />
            <strong>Type:</strong> <span data-bind="text: $root.Drone.Type"></span><br />
            <strong>Description:</strong> <span data-bind="text: $root.Drone.Description"></span><br />
            <strong>Size:</strong> <span data-bind="text: $root.Drone.Size"></span><br />
            <strong>Controller:</strong> <span data-bind="text: $root.Drone.Controller"></span><br />
            <strong>ESC:</strong> <span data-bind="text: $root.Drone.ESC"></span><br />
            <strong>Rotors:</strong> <span data-bind="text: $root.Drone.Rotors"></span><br />
        </div>
        <input id="SendButton" type="submit" value="Save" class="btn" data-bind="click: Send" />

    </div>
    <div style="padding: 16px; margin: 16px">
        <input class="ShowBasics btn" type="button" value="Back" data-bind="click: PreviousPage" />
        <input class="ShowParts btn" type="button" value="Next" data-bind="click: NextPage" />
    </div>
</div>

<script src="~/ViewModels/CreateDroneViewModel.js"></script>

DroneBook.WebUI/Views/Drone/Detail.cshtml
@model DroneBook.BusinessLogic.Services.Drone
@{
    ViewBag.Title = "Detail";
}

<h2>Detail</h2>
<div>
    <table class="table-condensed">
        <tr>
            <th>Name</th>
            <td>@Model.Name</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>@Model.Description</td>
        </tr>
    </table>
</div>


















<!--
<script>
    var DetailDroneViewModel = {
        id: window.location.pathname.substring(window.location.pathname.lastIndexOf('/') + 1),
        cos : "asd",

        DroneCreate : function(data) {
            var self = this;
            self.Name = data.name;
            self.Description = data.description;
        },

        DownloadData: function () {
            console.log(this);
            $.getJSON("http://localhost:50644/api/createdroneapi"+id, function (data) {
                console.log(data.toLowerCase());
                this.Drone = new DroneCreate(data);
                console.log(data);
            });
            ko.applyBindings(this.Drone);
        }
    };

    
    DetailDroneViewModel.DownloadData();
    //onsole.log(root.id);
    

</script>
    -->

DroneBook.WebUI/Views/Drone/List.cshtml
@model DroneBook.WebUI.ViewModels.DroneListViewModel
@{
    ViewBag.Title = "List of drones";
}

<div class="item-holder">
    <button type="button" class="btn-primary" onclick="location.href='@Url.Action("Create","CreateDrone")'">Create new</button>
</div>
<div data-bind="foreach: drones">
    <div class="item-holder">
        <div style="display: inline-block">
            <img class="image-holder" src="http://fandimefilmu.cz/assets/images/emptyAvatar.jpg" />
        </div>
        <div class="item-holder-top" style="display: inline-block">
            <div style="display: none" data-bind="text: Id"></div>

            <h4 class="h4" data-bind="text: Name"></h4>
            <div data-bind="text: Description"></div>
            <div data-bind="text: Type"></div>
            <div data-bind="text: Size"></div>
        </div>
        <div style="float: right; display: inline-block; vertical-align: top; margin-left: 16px">
            <input style="float: right" type="submit" value="Delete" class="btn-primary" data-bind="click: function(){ Delete($element) }, attr: { 'data-Id': Id }" />
        </div>
    </div>
</div>


<script>
    function ViewModel(data) {
        var self = this;
        self.drones = (JSON.parse(data));
    }

    $.getJSON("http://localhost:50644/api/createdroneapi", function (data) {
        console.log(data.toLowerCase());
        ko.applyBindings(new ViewModel(data));
    });



    function Delete(element) {
        var id = $(element).attr("data-id");

        var postUrl = "http://localhost:50644/api/CreateDroneApi/" + id.toString();
        $.ajax(postUrl, {
            data: ko.toJSON(),
            type: "Delete",
            contentType: "application/json",
            success: function () {
                //confirm("Twój dron został usunięty poprawnie!");
                window.location = "/";
            },
            error: function () {
                confirm("Nie udało się usunąć");
            }
        });
    }
</script>

DroneBook.WebUI/Views/Proby/Index.cshtml
@model DroneBook.WebUI.Controllers.ProbyViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Proby</h2>
<h2>Model:</h2>
<p>First name: <input data-bind="value: firstName" /></p>
<p>Last name: <input data-bind="value: lastName" /></p>
<h2>Hello, <span data-bind="text: fullName"> </span>!</h2>

<script>
    var ViewModel = function (first, last) {
        self = this;
        self.firstName = ko.observable(first);
        self.lastName = ko.observable(last);

        this.fullName = ko.pureComputed(function () {
            // Knockout tracks dependencies automatically. It knows that fullName depends on firstName and lastName, because these get called when evaluating fullName.
            return self.firstName() + " " + self.lastName();
        }, self);
    };

    $.getJSON("http://localhost:50644/api/defaulttest", function (data) {
        console.log("jest " + data[0]);
        ko.applyBindings(new ViewModel(data[0], data[1] + " " + data[2]));
    });
</script>

DroneBook.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/knockout-3.3.0.debug.js"></script>
    <script src="~/Scripts/knockout.mapping-latest.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DroneBook", "List", "Drone", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
</body>
</html>